# Generated by Django 5.1.4 on 2025-01-23 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FileUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IP', models.CharField(max_length=15)),
                ('File', models.CharField(max_length=128)),
                ('token', models.CharField(max_length=512)),
            ],
        ),
    ]
