# Generated by Django 5.1.4 on 2025-02-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileunit',
            name='server_ip',
            field=models.CharField(default='192.168.1.1', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileunit',
            name='subnet',
            field=models.CharField(default='NULL', max_length=15),
            preserve_default=False,
        ),
    ]
