# Generated by Django 5.1.4 on 2025-02-03 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_fileunit_server_ip_fileunit_subnet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileunit',
            name='subnet',
        ),
    ]
