# Generated by Django 5.1.4 on 2025-04-05 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_fileunit_subnet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileunit',
            name='File',
            field=models.CharField(max_length=512),
        ),
    ]
